### ISSUE TITLE
Use candid as auth backend for external application

### ISSUE THREAD

**Issue by kmadac** [CanonicalLtd/candid#179]
Hello,

we have internal candid server configured to use ldap and  static users as identity providers. I would like to use same candid instance as a authentication backend for existing python web application written in flask. That app has its own login form where users enter credentials.

**Is there a way how verify that these entered user credentials (username/password) are valid in Candid without necessity to redirect to Candid own login page?**
 
I have seen in a code that there is some kind of BasicAuth functionality, but it seems that it is only usable for admin user and probably will be removed in future. 

Thanks

**Comment by mhilton** [comment]
Hi @kmadac.

Your described use case isn't what the system was designed for, and it certainly wouldn't work in the general case. The static and LDAP identity providers might be possible to get to work. Even so it would probably be more complicated to interact with than you would like.

That said, ff you start the macaroon discharge as normal, but send an `Accept: application/json` header to the returned VisitURL. Then instead of requiring a web-browser to interact with the login page, you could just post a username and password to the URL returned in the json body. For this to work you still need to handle all redirects and cookies, and you would still need to create and discharge macaroons. This would be a lot of infrastructure on the application side.

The IDP code in `idp/static` and `idp/ldap` does have a well-defined, if somewhat esoteric, interface. You might find that you can create a simpler solution by wrapping the IDPs you are interested in in some new server code that provides the interface your application requires.

**Comment by mhilton** [comment]
I'm going to close this issue in preparation for archiving this repository. All future development will happen in https://github.com/canonical/candid please feel free to continue this discussion there if you wish.
